### Global variables
@baseUrl = http://localhost:8080
@apiKey = {{createAccount.response.body.api_key}}

### Create a new account
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com"
}

### Get account details
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}